# This rule is not used by the project aknsc itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the nhudson.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aknsc
    app.kubernetes.io/managed-by: kustomize
  name: namespaceclass-editor-role
rules:
- apiGroups:
  - nhudson.dev
  resources:
  - namespaceclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nhudson.dev
  resources:
  - namespaceclasses/status
  verbs:
  - get
