apiVersion: nhudson.dev/v1alpha1
kind: NamespaceClass
metadata:
  name: internal-network
  labels:
    app.kubernetes.io/name: aknsc
    app.kubernetes.io/managed-by: kustomize
spec:
  resources:
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-vpn-ingress-egress
      spec:
        podSelector: {}
        policyTypes:
          - Ingress
          - Egress
        ingress:
          - from:
              - ipBlock:
                  cidr: 10.0.0.0/8
        egress:
          - to:
              - ipBlock:
                  cidr: 10.0.0.0/8
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: internal-service-account
        annotations:
          description: "Service account for internal network resources"
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: internal-config
      data:
        environment: "internal"
        network.type: "vpn-only"
        allowed.cidrs: "10.0.0.0/8"
        security.level: "high"
