apiVersion: nhudson.dev/v1alpha1
kind: NamespaceClass
metadata:
  name: public-network
  labels:
    app.kubernetes.io/name: aknsc
    app.kubernetes.io/managed-by: kustomize
spec:
  resources:
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-all-ingress
      spec:
        podSelector: {}
        ingress:
          - {}
        policyTypes:
          - Ingress
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: public-service-account
        annotations:
          description: "Service account for public network resources"
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: public-config
      data:
        environment: "public"
        network.type: "public"
        security.level: "medium"
        allowed.ports: "80,443"
